### ISSUE TITLE
Generator writing test files to lib directory

### ISSUE THREAD

**Issue by nikfp** [PracticeCraft/spirit#13]
![image](https://github.com/user-attachments/assets/e8d22737-8feb-4e6d-9839-a2a4552434fd)

had a report from Reddit that the generator wasn't placing test files correctly. Can't investigate for a bit though.

**Comment by waseem-medhat** [comment]
I just looked at it, and the issue is due to the test file having `.ex` as the extension. Will fix right away.

**Comment by nikfp** [comment]
That would be my mistake then, I'm the one that wrote the test file. 

If you are fixing, please proceed.
