### ISSUE TITLE
Clean up the initial Mix generator code

### ISSUE THREAD

**Issue by waseem-medhat** [PracticeCraft/spirit#5]
This should include:
- Fixing some compiler warnings (unused variables)
- Adding docs/moduledocs
- (Possibly) renaming variables or functions if they need to be more descriptive

@nikfp let me know if there's anything else you want to be done under this issue

**Comment by nikfp** [comment]
This looks like the list I had in mind. Sorry the initial code was in that condition, I wish I had more time to engage. I'm working on some things outside of programming that will hopefully free up some of my time soon.

**Comment by waseem-medhat** [comment]
We're making progress and that's what matters.
